/**
 * POST /internal/clients — agent-key registration (INTERNAL ONLY).
 *
 * agent-service calls this when a user signs up with accountType "agent":
 * a fresh MCP API key is generated by agent-service (shown to the user ONCE),
 * and its hash is registered here, bound to that user's room via
 * agentName = "user:<uid>". From then on the agent's own X-API-Key works
 * directly against /mcp and /rest — with room isolation enforced in the tools.
 *
 * Security: guarded by a timing-safe comparison of X-Internal-Key against
 * MCP_SERVER_INTERNAL_API_KEY (the same secret the internal api client uses).
 * The RAW key travels once over the compose-internal network and is stored
 * ONLY as its sha256(salt:key) hash — identical to the seed/ensureApiClient path.
 */
import type { NextFunction, Request, Response, Router } from 'express';
import { Router as createRouter } from 'express';
import { createHash, timingSafeEqual } from 'node:crypto';
import { ensureApiClient } from '../scripts/seedCatalog';

const AGENT_NAME_RE = /^user:[a-f0-9]{24}$/;

function secretsMatch(provided: string, expected: string): boolean {
  const a = createHash('sha256').update(provided).digest();
  const b = createHash('sha256').update(expected).digest();
  return timingSafeEqual(a, b);
}

export function buildInternalRouter(salt: string, internalKey: string): Router {
  const router = createRouter();

  router.post('/internal/clients', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const provided = req.header('x-internal-key');
      if (typeof provided !== 'string' || provided.length === 0 || !secretsMatch(provided, internalKey)) {
        res.status(401).json({ error: 'UNAUTHORIZED' });
        return;
      }
      const body = (req.body ?? {}) as { apiKey?: unknown; agentName?: unknown; rateLimitPerMinute?: unknown };
      const apiKey = body.apiKey;
      const agentName = body.agentName;
      if (typeof apiKey !== 'string' || apiKey.length < 16 || apiKey.length > 256) {
        res.status(400).json({ error: 'INVALID_API_KEY', hint: 'apiKey must be 16-256 chars.' });
        return;
      }
      if (typeof agentName !== 'string' || !AGENT_NAME_RE.test(agentName)) {
        res.status(400).json({ error: 'INVALID_AGENT_NAME', hint: 'agentName must be the user room: "user:<uid>".' });
        return;
      }
      const rateLimit =
        typeof body.rateLimitPerMinute === 'number' && Number.isFinite(body.rateLimitPerMinute)
          ? Math.max(1, Math.min(Math.floor(body.rateLimitPerMinute), 1000))
          : 120;
      await ensureApiClient(apiKey, salt, agentName, rateLimit);
      res.status(201).json({ ok: true, agentName, rateLimitPerMinute: rateLimit });
    } catch (err) {
      next(err);
    }
  });

  return router;
}
